### PR TITLE
Enable changing the route group prefix

### PR DESCRIPTION
**Pull request by tormjens**
Thanks for a great package.

While using this I was annoyed that the name of the route group was pre-defined as it did not match up with the route naming convention for the rest of my application.

This PR solves this by allowing the prefix to be changed via a config file.

By default the routes returning the JSON responses are prefixed with `galahad/addressing`. You can change this by creating a config file (`addressing.php`) in your `config` directory with these contents.

```php 
<?php

return [
    'route' => [
        'prefix' => 'countries' // change this to whatever you'd like
    ],
];
```

### CODE REVIEW

**Comment by inxilpro** [comment]
This looks great! Thanks for contributing. 

Would you be able add the config to the project per [the Laravel docs](https://laravel.com/docs/5.6/packages#configuration)? Basically a `publishes()` and `mergeConfigFrom()` call…

**Comment by tormjens** [comment]
Done! :)

**Comment by inxilpro** [comment]
Made a few minor changes. Do you see any issue with them?

**Comment by tormjens** [comment]
Looks good 👍🏻

**Pull request merged**
